use crate::ast::*;
use crate::types::Type;

pub fn generate_rust(program: &Program) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Volt v0.1\n\n");

    for declaration in &program.declarations {
        match declaration {
            Decl::Type(type_decl) => {
                emit_type_decl(&mut out, type_decl);
                out.push('\n');
            }
            Decl::Function(function) => {
                emit_function(&mut out, function);
                out.push('\n');
            }
            Decl::Route(route) => {
                emit_route(&mut out, route);
                out.push('\n');
            }
        }
    }

    out
}

fn emit_route(out: &mut String, route: &RouteDecl) {
    let fn_name = route_function_name(route);
    out.push_str("// Native Volt route scaffold.\n");
    out.push_str("// Wire this function into an Axum Router once the HTTP runtime lands.\n");
    out.push_str(&format!(
        "// route {} \"{}\" -> {} {}\n",
        http_method(route.method).to_uppercase(),
        route.path,
        route.ok_status,
        rust_type(&route.ok_type)
    ));
    if !route.effects.is_empty() {
        out.push_str(&format!("// effects: {}\n", route.effects.join(", ")));
    }
    out.push_str(&format!("async fn {fn_name}(\n"));
    for field in &route.params {
        out.push_str(&format!(
            "    // axum::extract::Path({}): axum::extract::Path<{}>,\n",
            field.name,
            rust_type(&field.ty)
        ));
    }
    if let Some(body_type) = &route.body_type {
        out.push_str(&format!(
            "    // axum::Json(body): axum::Json<{}>,\n",
            rust_type(body_type)
        ));
    }
    out.push_str("    // axum::extract::State(state): axum::extract::State<AppState>,\n");
    out.push_str(") -> impl axum::response::IntoResponse {\n");
    out.push_str("    // TODO(v0.1): lower Volt route statements into Axum handler code.\n");
    out.push_str(&format!(
        "    // Router::new().route(\"{}\", axum::routing::{}({fn_name}))\n",
        route.path,
        http_method(route.method)
    ));
    out.push_str("    axum::http::StatusCode::NOT_IMPLEMENTED\n");
    out.push_str("}\n");
}

fn emit_type_decl(out: &mut String, type_decl: &TypeDecl) {
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("struct {} {{\n", type_decl.name));
    for field in &type_decl.fields {
        out.push_str(&format!("    {}: {},\n", field.name, rust_type(&field.ty)));
    }
    out.push_str("}\n");
}

fn emit_function(out: &mut String, function: &FunctionDecl) {
    let params = function
        .params
        .iter()
        .map(|param| format!("{}: {}", param.name, rust_type(&param.ty)))
        .collect::<Vec<_>>()
        .join(", ");

    if matches!(function.return_type, Type::Void) {
        out.push_str(&format!("fn {}({}) {{\n", function.name, params));
    } else {
        out.push_str(&format!(
            "fn {}({}) -> {} {{\n",
            function.name,
            params,
            rust_type(&function.return_type)
        ));
    }

    for stmt in &function.body {
        emit_stmt(out, stmt, 1);
    }
    out.push_str("}\n");
}

fn emit_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    let pad = "    ".repeat(indent);
    match stmt {
        Stmt::Var {
            mutable,
            name,
            expr,
            ..
        } => {
            let mutability = if *mutable { " mut" } else { "" };
            out.push_str(&format!(
                "{pad}let{mutability} {name} = {};\n",
                emit_expr(expr)
            ));
        }
        Stmt::Return { expr, .. } => {
            out.push_str(&format!("{pad}return {};\n", emit_expr(expr)));
        }
        Stmt::If {
            condition,
            then_body,
            else_body,
            ..
        } => {
            out.push_str(&format!("{pad}if {} {{\n", emit_expr(condition)));
            for stmt in then_body {
                emit_stmt(out, stmt, indent + 1);
            }
            if else_body.is_empty() {
                out.push_str(&format!("{pad}}}\n"));
            } else {
                out.push_str(&format!("{pad}}} else {{\n"));
                for stmt in else_body {
                    emit_stmt(out, stmt, indent + 1);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
        }
        Stmt::Expr { expr, .. } => {
            out.push_str(&format!("{pad}{};\n", emit_expr(expr)));
        }
    }
}

fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Int { value, .. } => value.to_string(),
        Expr::Float { value, .. } => {
            let text = value.to_string();
            if text.contains('.') {
                text
            } else {
                format!("{text}.0")
            }
        }
        Expr::String { value, .. } => format!("{:?}.to_string()", value),
        Expr::Bool { value, .. } => value.to_string(),
        Expr::Var { name, .. } => name.clone(),
        Expr::Binary {
            left, op, right, ..
        } => format!(
            "{} {} {}",
            emit_expr(left),
            rust_binary_op(*op),
            emit_expr(right)
        ),
        Expr::Call { callee, args, .. } => match callee.as_str() {
            "print" => format!("println!(\"{{:?}}\", {})", emit_expr(&args[0])),
            "ok" => format!("Ok({})", emit_expr(&args[0])),
            "err" => format!("Err({})", emit_expr(&args[0])),
            _ => format!(
                "{}({})",
                callee,
                args.iter().map(emit_expr).collect::<Vec<_>>().join(", ")
            ),
        },
        Expr::Try { expr, .. } => format!("{}?", emit_expr(expr)),
        Expr::ObjectLiteral { fields, .. } => {
            let body = fields
                .iter()
                .map(|field| match field {
                    ObjectField::Named { name, expr, .. } => format!("{name}: {}", emit_expr(expr)),
                    ObjectField::Spread { expr, .. } => format!("..{}", emit_expr(expr)),
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {body} }}")
        }
        Expr::StructLiteral { name, fields, .. } => {
            let body = fields
                .iter()
                .map(|field| format!("{}: {}", field.name, emit_expr(&field.expr)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{name} {{ {body} }}")
        }
        Expr::FieldAccess { object, field, .. } => format!("{}.{}", emit_expr(object), field),
    }
}

fn route_function_name(route: &RouteDecl) -> String {
    let mut name = http_method(route.method).to_string();
    for part in route.path.trim_matches('/').split('/') {
        if part.is_empty() {
            continue;
        }
        let cleaned = part
            .trim_matches('{')
            .trim_matches('}')
            .chars()
            .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
            .collect::<String>();
        if !cleaned.is_empty() {
            name.push('_');
            name.push_str(&cleaned);
        }
    }
    name.push_str("_route");
    name
}

fn http_method(method: HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "get",
        HttpMethod::Post => "post",
        HttpMethod::Put => "put",
        HttpMethod::Patch => "patch",
        HttpMethod::Delete => "delete",
    }
}

fn rust_binary_op(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        BinaryOp::Eq => "==",
        BinaryOp::NotEq => "!=",
        BinaryOp::Lt => "<",
        BinaryOp::Gt => ">",
        BinaryOp::LtEq => "<=",
        BinaryOp::GtEq => ">=",
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::I32 => "i32".to_string(),
        Type::I64 => "i64".to_string(),
        Type::U32 => "u32".to_string(),
        Type::U64 => "u64".to_string(),
        Type::F32 => "f32".to_string(),
        Type::F64 => "f64".to_string(),
        Type::Bool => "bool".to_string(),
        Type::String => "String".to_string(),
        Type::Void => "()".to_string(),
        Type::Result(ok, err) => format!("Result<{}, {}>", rust_type(ok), rust_type(err)),
        Type::Struct(name) => name.clone(),
        Type::InferInt => "i32".to_string(),
        Type::InferFloat => "f64".to_string(),
        Type::Unknown => "()".to_string(),
    }
}
