use crate::ast::*;
use crate::diagnostics::{Diagnostic, DiagnosticBag, SourceFile, Span};
use crate::types::Type;
use std::collections::HashMap;

pub fn generate_rust(program: &Program) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Volt v0.1\n\n");
    let symbols = CodegenSymbols::from_program(program);

    for declaration in &program.declarations {
        match declaration {
            Decl::Import(_) => {}
            Decl::Type(type_decl) => {
                emit_type_decl(&mut out, type_decl);
                out.push('\n');
            }
            Decl::Error(error_decl) => {
                emit_error_decl(&mut out, error_decl, false);
                out.push('\n');
            }
            Decl::Function(function) => {
                emit_function(&mut out, function, &symbols);
                out.push('\n');
            }
            Decl::Route(route) => {
                emit_route(&mut out, route);
                out.push('\n');
            }
        }
    }

    out
}

pub fn generate_axum_server(
    program: &Program,
    source: &SourceFile,
) -> Result<String, DiagnosticBag> {
    let mut lowering = AxumLowering {
        source,
        diagnostics: DiagnosticBag::new(),
    };
    let rust = lowering.generate(program);
    if lowering.diagnostics.is_empty() {
        Ok(rust)
    } else {
        Err(lowering.diagnostics)
    }
}

struct AxumLowering<'a> {
    source: &'a SourceFile,
    diagnostics: DiagnosticBag,
}

#[derive(Debug, Clone, Default)]
struct CodegenSymbols {
    functions: HashMap<String, FunctionSigInfo>,
    structs: HashMap<String, HashMap<String, Type>>,
    errors: HashMap<String, HashMap<String, HashMap<String, Type>>>,
}

#[derive(Debug, Clone)]
struct FunctionSigInfo {
    return_type: Type,
}

impl CodegenSymbols {
    fn from_program(program: &Program) -> Self {
        let mut symbols = CodegenSymbols::default();
        for declaration in &program.declarations {
            match declaration {
                Decl::Function(function) => {
                    symbols.functions.insert(
                        function.name.clone(),
                        FunctionSigInfo {
                            return_type: function.return_type.clone(),
                        },
                    );
                }
                Decl::Type(type_decl) => {
                    symbols.structs.insert(
                        type_decl.name.clone(),
                        type_decl
                            .fields
                            .iter()
                            .map(|field| (field.name.clone(), field.ty.clone()))
                            .collect(),
                    );
                }
                Decl::Error(error_decl) => {
                    symbols.errors.insert(
                        error_decl.name.clone(),
                        error_decl
                            .variants
                            .iter()
                            .map(|variant| {
                                (
                                    variant.name.clone(),
                                    variant
                                        .fields
                                        .iter()
                                        .map(|field| (field.name.clone(), field.ty.clone()))
                                        .collect(),
                                )
                            })
                            .collect(),
                    );
                }
                Decl::Import(_) | Decl::Route(_) => {}
            }
        }
        symbols
    }
}

impl AxumLowering<'_> {
    fn generate(&mut self, program: &Program) -> String {
        let routes = program
            .declarations
            .iter()
            .filter_map(|decl| match decl {
                Decl::Route(route) => Some(route),
                _ => None,
            })
            .collect::<Vec<_>>();

        let mut out = String::new();
        out.push_str("// Generated by Volt v0.1\n");
        out.push_str("use axum::extract::{Path, Query, State};\n");
        out.push_str("use axum::http::StatusCode;\n");
        out.push_str("use axum::response::IntoResponse;\n");
        out.push_str("use axum::routing::{delete, get, patch, post, put};\n");
        out.push_str("use axum::Json;\n");
        out.push_str("use serde::{Deserialize, Serialize};\n\n");
        out.push_str("#[derive(Debug, Clone, Default)]\n");
        out.push_str("pub struct AppState {}\n\n");
        out.push_str("#[derive(Debug, Clone)]\n");
        out.push_str("pub struct RequestCtx {\n");
        out.push_str("    pub state: AppState,\n");
        out.push_str("}\n\n");
        out.push_str("impl RequestCtx {\n");
        out.push_str("    pub fn new(state: AppState) -> Self {\n");
        out.push_str("        Self { state }\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        for declaration in &program.declarations {
            match declaration {
                Decl::Type(type_decl) => {
                    emit_api_type_decl(&mut out, type_decl);
                    out.push('\n');
                }
                Decl::Error(error_decl) => {
                    emit_error_decl(&mut out, error_decl, true);
                    out.push('\n');
                }
                _ => {}
            }
        }

        for route in &routes {
            self.emit_route_params(&mut out, route);
            self.emit_route_query(&mut out, route);
        }

        for route in &routes {
            self.emit_route_handler(&mut out, route);
            out.push('\n');
        }

        for route in &routes {
            self.emit_route_error_status(&mut out, route);
        }

        self.emit_router(&mut out, &routes);
        emit_async_main(&mut out);
        out
    }

    fn emit_route_params(&mut self, out: &mut String, route: &RouteDecl) {
        if route.params.is_empty() {
            return;
        }
        out.push_str("#[derive(Debug, Clone, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", route_params_name(route)));
        for field in &route.params {
            out.push_str(&format!(
                "    pub {}: {},\n",
                field.name,
                rust_type(&field.ty)
            ));
        }
        out.push_str("}\n\n");
    }

    fn emit_route_query(&mut self, out: &mut String, route: &RouteDecl) {
        if route.query.is_empty() {
            return;
        }
        out.push_str("#[derive(Debug, Clone, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", route_query_name(route)));
        for field in &route.query {
            out.push_str(&format!(
                "    pub {}: {},\n",
                field.name,
                rust_type(&field.ty)
            ));
        }
        out.push_str("}\n\n");
    }

    fn emit_route_handler(&mut self, out: &mut String, route: &RouteDecl) {
        let fn_name = route_function_name(route);
        out.push_str(&format!("async fn {fn_name}(\n"));
        if !route.params.is_empty() {
            out.push_str(&format!(
                "    Path(params): Path<{}>,\n",
                route_params_name(route)
            ));
        }
        if !route.query.is_empty() {
            out.push_str(&format!(
                "    Query(query): Query<{}>,\n",
                route_query_name(route)
            ));
        }
        out.push_str("    State(state): State<AppState>,\n");
        if let Some(body_type) = &route.body_type {
            out.push_str(&format!(
                "    Json(body): Json<{}>,\n",
                rust_type(body_type)
            ));
        }
        out.push_str(") -> impl IntoResponse {\n");
        out.push_str("    let ctx = RequestCtx::new(state);\n");
        out.push_str("    let _ = &ctx;\n");

        let Some(return_expr) = self.emit_route_statements(out, &route.statements) else {
            out.push_str("    StatusCode::INTERNAL_SERVER_ERROR.into_response()\n");
            out.push_str("}\n");
            return;
        };

        out.push_str(&format!("    let value = {return_expr};\n"));
        out.push_str(&format!(
            "    ({}, Json(value)).into_response()\n",
            status_code(route.ok_status)
        ));
        out.push_str("}\n");
    }

    fn emit_route_statements(&mut self, out: &mut String, statements: &[Stmt]) -> Option<String> {
        let mut return_expr = None;
        for stmt in statements {
            match stmt {
                Stmt::Var {
                    mutable,
                    name,
                    expr,
                    span,
                    ..
                } => {
                    let Some(value) = self.lower_route_expr(expr) else {
                        self.unsupported(*span);
                        continue;
                    };
                    let mutability = if *mutable { " mut" } else { "" };
                    out.push_str(&format!("    let{mutability} {name} = {value};\n"));
                }
                Stmt::Return { expr, span } => {
                    let Some(ok_expr) = route_ok_expr(expr) else {
                        self.unsupported(*span);
                        continue;
                    };
                    return_expr = self.lower_route_expr(ok_expr);
                    if return_expr.is_none() {
                        self.unsupported(ok_expr.span());
                    }
                }
                _ => self.unsupported(stmt_span(stmt)),
            }
        }
        return_expr
    }

    fn lower_route_expr(&mut self, expr: &Expr) -> Option<String> {
        match expr {
            Expr::Int { value, .. } => Some(value.to_string()),
            Expr::Float { value, .. } => Some(value.to_string()),
            Expr::String { value, .. } => Some(format!("{value:?}.to_string()")),
            Expr::Bool { value, .. } => Some(value.to_string()),
            Expr::Var { name, .. } => Some(name.clone()),
            Expr::FieldAccess { object, field, .. } => {
                let base = self.lower_route_expr(object)?;
                Some(format!("{base}.{field}"))
            }
            Expr::StructLiteral { name, fields, .. } => {
                let mut parts = Vec::new();
                for field in fields {
                    let value = self.lower_route_expr(&field.expr)?;
                    parts.push(format!("{}: {}", field.name, value));
                }
                Some(format!("{name} {{ {} }}", parts.join(", ")))
            }
            Expr::Call { callee, args, .. } if callee != "ok" && callee != "err" => {
                let mut lowered = Vec::new();
                for arg in args {
                    lowered.push(self.lower_route_expr(arg)?);
                }
                Some(format!("{callee}({})", lowered.join(", ")))
            }
            _ => None,
        }
    }

    fn emit_router(&mut self, out: &mut String, routes: &[&RouteDecl]) {
        out.push_str("fn build_router(state: AppState) -> axum::Router {\n");
        out.push_str("    axum::Router::new()\n");
        for route in routes {
            out.push_str(&format!(
                "        .route({:?}, {}({}))\n",
                route.path,
                http_method(route.method),
                route_function_name(route)
            ));
        }
        out.push_str("        .with_state(state)\n");
        out.push_str("}\n\n");
    }

    fn emit_route_error_status(&mut self, out: &mut String, route: &RouteDecl) {
        let Some(Type::Struct(error_name)) = &route.error_type else {
            return;
        };
        if route.errors.is_empty() {
            return;
        }

        out.push_str(&format!(
            "fn {}(error: &{}) -> StatusCode {{\n",
            route_error_status_fn(route),
            error_name
        ));
        out.push_str("    match error {\n");
        for mapping in &route.errors {
            out.push_str(&format!(
                "        {}::{} {{ .. }} => {},\n",
                error_name,
                mapping.name,
                status_code(mapping.status)
            ));
        }
        out.push_str("        _ => StatusCode::INTERNAL_SERVER_ERROR,\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    fn unsupported(&mut self, span: Span) {
        self.diagnostics.push(Diagnostic::new(
            "EHTTPLOWER001",
            "unsupported route body expression for Axum lowering",
            self.source,
            span,
            Some("use const bindings and `return ok(...)` with literals, field access, calls, or struct literals".to_string()),
        ));
    }
}

fn emit_api_type_decl(out: &mut String, type_decl: &TypeDecl) {
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", type_decl.name));
    for field in &type_decl.fields {
        out.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            rust_type(&field.ty)
        ));
    }
    out.push_str("}\n");
}

fn emit_async_main(out: &mut String) {
    out.push_str("#[tokio::main]\n");
    out.push_str("async fn main() {\n");
    out.push_str("    let state = AppState::default();\n");
    out.push_str("    let app = build_router(state);\n\n");
    out.push_str("    let addr = std::env::var(\"VLT_ADDR\")\n");
    out.push_str("        .unwrap_or_else(|_| \"0.0.0.0:8080\".to_string());\n\n");
    out.push_str("    let listener = tokio::net::TcpListener::bind(&addr)\n");
    out.push_str("        .await\n");
    out.push_str("        .expect(\"failed to bind TCP listener\");\n\n");
    out.push_str("    println!(\"Volt server listening on http://{}\", addr);\n\n");
    out.push_str("    axum::serve(listener, app)\n");
    out.push_str("        .await\n");
    out.push_str("        .expect(\"server failed\");\n");
    out.push_str("}\n");
}

fn emit_route(out: &mut String, route: &RouteDecl) {
    let fn_name = route_function_name(route);
    out.push_str("// Native Volt route scaffold.\n");
    out.push_str("// Wire this function into an Axum Router once the HTTP runtime lands.\n");
    out.push_str(&format!(
        "// route {} \"{}\" -> {} {}\n",
        http_method(route.method).to_uppercase(),
        route.path,
        route.ok_status,
        rust_type(&route.ok_type)
    ));
    if !route.effects.is_empty() {
        out.push_str(&format!("// effects: {}\n", route.effects.join(", ")));
    }
    if let Some(error_type) = &route.error_type {
        out.push_str(&format!("// errors: {}\n", rust_type(error_type)));
        for mapping in &route.errors {
            out.push_str(&format!("//   {} -> {}\n", mapping.name, mapping.status));
        }
    }
    out.push_str(&format!("async fn {fn_name}(\n"));
    for field in &route.params {
        out.push_str(&format!(
            "    // axum::extract::Path({}): axum::extract::Path<{}>,\n",
            field.name,
            rust_type(&field.ty)
        ));
    }
    if let Some(body_type) = &route.body_type {
        out.push_str(&format!(
            "    // axum::Json(body): axum::Json<{}>,\n",
            rust_type(body_type)
        ));
    }
    out.push_str("    // axum::extract::State(state): axum::extract::State<AppState>,\n");
    out.push_str(") -> impl axum::response::IntoResponse {\n");
    out.push_str("    // TODO(v0.1): lower Volt route statements into Axum handler code.\n");
    out.push_str(&format!(
        "    // Router::new().route(\"{}\", axum::routing::{}({fn_name}))\n",
        route.path,
        http_method(route.method)
    ));
    out.push_str("    axum::http::StatusCode::NOT_IMPLEMENTED\n");
    out.push_str("}\n");
}

fn emit_type_decl(out: &mut String, type_decl: &TypeDecl) {
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("struct {} {{\n", type_decl.name));
    for field in &type_decl.fields {
        out.push_str(&format!("    {}: {},\n", field.name, rust_type(&field.ty)));
    }
    out.push_str("}\n");
}

fn emit_error_decl(out: &mut String, error_decl: &ErrorDecl, public: bool) {
    out.push_str("#[derive(Debug, Clone");
    if public {
        out.push_str(", Serialize, Deserialize");
    }
    out.push_str(")]\n");
    let vis = if public { "pub " } else { "" };
    out.push_str(&format!("{vis}enum {} {{\n", error_decl.name));
    for variant in &error_decl.variants {
        let fields = variant
            .fields
            .iter()
            .map(|field| format!("{}: {}", field.name, rust_type(&field.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    {} {{ {} }},\n", variant.name, fields));
    }
    out.push_str("}\n");
}

fn emit_function(out: &mut String, function: &FunctionDecl, symbols: &CodegenSymbols) {
    let params = function
        .params
        .iter()
        .map(|param| format!("{}: {}", param.name, rust_type(&param.ty)))
        .collect::<Vec<_>>()
        .join(", ");

    if matches!(function.return_type, Type::Void) {
        out.push_str(&format!("fn {}({}) {{\n", function.name, params));
    } else {
        out.push_str(&format!(
            "fn {}({}) -> {} {{\n",
            function.name,
            params,
            rust_type(&function.return_type)
        ));
    }

    let mut env = function
        .params
        .iter()
        .map(|param| (param.name.clone(), param.ty.clone()))
        .collect::<HashMap<_, _>>();
    for stmt in &function.body {
        emit_stmt(out, stmt, 1, &function.return_type, &mut env, symbols);
    }
    out.push_str("}\n");
}

fn emit_stmt(
    out: &mut String,
    stmt: &Stmt,
    indent: usize,
    return_type: &Type,
    env: &mut HashMap<String, Type>,
    symbols: &CodegenSymbols,
) {
    let pad = "    ".repeat(indent);
    match stmt {
        Stmt::Var {
            mutable,
            name,
            annotation,
            expr,
            ..
        } => {
            let mutability = if *mutable { " mut" } else { "" };
            out.push_str(&format!(
                "{pad}let{mutability} {name} = {};\n",
                emit_expr_expected(expr, annotation.as_ref(), env, symbols)
            ));
            let ty = annotation
                .clone()
                .unwrap_or_else(|| materialize_codegen_type(infer_expr_type(expr, env, symbols)));
            env.insert(name.clone(), ty);
        }
        Stmt::Return { expr, .. } => {
            out.push_str(&format!(
                "{pad}return {};\n",
                emit_expr_expected(expr, Some(return_type), env, symbols)
            ));
        }
        Stmt::If {
            condition,
            then_body,
            else_body,
            ..
        } => {
            if let Some((name, inner)) = positive_option_condition(condition, env) {
                out.push_str(&format!("{pad}if let Some({name}) = {name} {{\n"));
                let mut then_env = env.clone();
                then_env.insert(name, inner);
                for stmt in then_body {
                    emit_stmt(out, stmt, indent + 1, return_type, &mut then_env, symbols);
                }
                if else_body.is_empty() {
                    out.push_str(&format!("{pad}}}\n"));
                } else {
                    out.push_str(&format!("{pad}}} else {{\n"));
                    let mut else_env = env.clone();
                    for stmt in else_body {
                        emit_stmt(out, stmt, indent + 1, return_type, &mut else_env, symbols);
                    }
                    out.push_str(&format!("{pad}}}\n"));
                }
            } else if let Some((name, inner)) = negative_option_condition(condition, env) {
                if else_body.is_empty() && always_returns_codegen(then_body) {
                    out.push_str(&format!(
                        "{pad}let {name} = if let Some({name}) = {name} {{\n"
                    ));
                    out.push_str(&format!("{pad}    {name}\n"));
                    out.push_str(&format!("{pad}}} else {{\n"));
                    let mut then_env = env.clone();
                    for stmt in then_body {
                        emit_stmt(out, stmt, indent + 1, return_type, &mut then_env, symbols);
                    }
                    out.push_str(&format!("{pad}}};\n"));
                    env.insert(name, inner);
                } else {
                    out.push_str(&format!(
                        "{pad}if {} {{\n",
                        emit_expr_expected(condition, Some(&Type::Bool), env, symbols)
                    ));
                    for stmt in then_body {
                        emit_stmt(out, stmt, indent + 1, return_type, env, symbols);
                    }
                    out.push_str(&format!("{pad}}}\n"));
                }
            } else {
                out.push_str(&format!(
                    "{pad}if {} {{\n",
                    emit_expr_expected(condition, Some(&Type::Bool), env, symbols)
                ));
                let mut then_env = env.clone();
                for stmt in then_body {
                    emit_stmt(out, stmt, indent + 1, return_type, &mut then_env, symbols);
                }
                if else_body.is_empty() {
                    out.push_str(&format!("{pad}}}\n"));
                } else {
                    out.push_str(&format!("{pad}}} else {{\n"));
                    let mut else_env = env.clone();
                    for stmt in else_body {
                        emit_stmt(out, stmt, indent + 1, return_type, &mut else_env, symbols);
                    }
                    out.push_str(&format!("{pad}}}\n"));
                }
            }
        }
        Stmt::Expr { expr, .. } => {
            out.push_str(&format!(
                "{pad}{};\n",
                emit_expr_expected(expr, None, env, symbols)
            ));
        }
    }
}

fn emit_expr_expected(
    expr: &Expr,
    expected: Option<&Type>,
    env: &HashMap<String, Type>,
    symbols: &CodegenSymbols,
) -> String {
    if let Some(Type::Option(inner)) = expected {
        if matches!(expr, Expr::Var { name, .. } if name == "none") {
            return "None".to_string();
        }
        let actual = infer_expr_type(expr, env, symbols);
        if !matches!(actual, Type::Option(_) | Type::None | Type::Unknown)
            && inner.is_assignable_from(&actual)
        {
            return format!("Some({})", emit_expr(expr, env, symbols));
        }
    }

    match expr {
        Expr::Call { callee, args, .. } if callee == "ok" && args.len() == 1 => {
            let ok_expected = match expected {
                Some(Type::Result(ok, _)) => Some(ok.as_ref()),
                _ => None,
            };
            format!(
                "Ok({})",
                emit_expr_expected(&args[0], ok_expected, env, symbols)
            )
        }
        Expr::Call { callee, args, .. } if callee == "err" && args.len() == 1 => {
            let err_expected = match expected {
                Some(Type::Result(_, err)) => Some(err.as_ref()),
                _ => None,
            };
            format!(
                "Err({})",
                emit_expr_expected(&args[0], err_expected, env, symbols)
            )
        }
        _ => emit_expr(expr, env, symbols),
    }
}

fn emit_expr(expr: &Expr, env: &HashMap<String, Type>, symbols: &CodegenSymbols) -> String {
    match expr {
        Expr::Int { value, .. } => value.to_string(),
        Expr::Float { value, .. } => {
            let text = value.to_string();
            if text.contains('.') {
                text
            } else {
                format!("{text}.0")
            }
        }
        Expr::String { value, .. } => format!("{:?}.to_string()", value),
        Expr::Bool { value, .. } => value.to_string(),
        Expr::Var { name, .. } if name == "none" => "None".to_string(),
        Expr::Var { name, .. } => name.clone(),
        Expr::Binary {
            left, op, right, ..
        } => format!(
            "{} {} {}",
            emit_expr(left, env, symbols),
            rust_binary_op(*op),
            emit_expr(right, env, symbols)
        ),
        Expr::Call { callee, args, .. } => match callee.as_str() {
            "print" => format!(
                "println!(\"{{:?}}\", {})",
                emit_expr(&args[0], env, symbols)
            ),
            "ok" => format!("Ok({})", emit_expr(&args[0], env, symbols)),
            "err" => format!("Err({})", emit_expr(&args[0], env, symbols)),
            _ if symbols.structs.contains_key(callee) && args.len() == 1 => {
                if let Some(fields) = object_fields_for_codegen(&args[0]) {
                    let body = fields
                        .iter()
                        .map(|field| {
                            format!("{}: {}", field.name, emit_expr(&field.expr, env, symbols))
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{callee} {{ {body} }}")
                } else {
                    format!(
                        "{}({})",
                        callee,
                        args.iter()
                            .map(|arg| emit_expr(arg, env, symbols))
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                }
            }
            _ => format!(
                "{}({})",
                callee,
                args.iter()
                    .map(|arg| emit_expr(arg, env, symbols))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
        },
        Expr::Try { expr, .. } => format!("{}?", emit_expr(expr, env, symbols)),
        Expr::ObjectLiteral { fields, .. } => {
            let body = fields
                .iter()
                .map(|field| match field {
                    ObjectField::Named { name, expr, .. } => {
                        format!("{name}: {}", emit_expr(expr, env, symbols))
                    }
                    ObjectField::Spread { expr, .. } => {
                        format!("..{}", emit_expr(expr, env, symbols))
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {body} }}")
        }
        Expr::StructLiteral { name, fields, .. } => {
            let body = fields
                .iter()
                .map(|field| format!("{}: {}", field.name, emit_expr(&field.expr, env, symbols)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{name} {{ {body} }}")
        }
        Expr::FieldAccess { object, field, .. } => {
            format!("{}.{}", emit_expr(object, env, symbols), field)
        }
        Expr::Unary { op, expr, .. } => match op {
            UnaryOp::Not => match infer_expr_type(expr, env, symbols) {
                Type::Option(_) => format!("{}.is_none()", emit_expr(expr, env, symbols)),
                _ => format!("!{}", emit_expr(expr, env, symbols)),
            },
        },
        Expr::ErrorVariantLiteral {
            error,
            variant,
            fields,
            ..
        } => {
            let body = fields
                .iter()
                .map(|field| format!("{}: {}", field.name, emit_expr(&field.expr, env, symbols)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{error}::{variant} {{ {body} }}")
        }
    }
}

fn infer_expr_type(expr: &Expr, env: &HashMap<String, Type>, symbols: &CodegenSymbols) -> Type {
    match expr {
        Expr::Int { .. } => Type::InferInt,
        Expr::Float { .. } => Type::InferFloat,
        Expr::String { .. } => Type::String,
        Expr::Bool { .. } => Type::Bool,
        Expr::Var { name, .. } if name == "none" => Type::None,
        Expr::Var { name, .. } => env.get(name).cloned().unwrap_or(Type::Unknown),
        Expr::Binary { op, .. } => match op {
            BinaryOp::Eq
            | BinaryOp::NotEq
            | BinaryOp::Lt
            | BinaryOp::Gt
            | BinaryOp::LtEq
            | BinaryOp::GtEq => Type::Bool,
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul | BinaryOp::Div => Type::Unknown,
        },
        Expr::Call { callee, args, .. } if callee == "ok" && args.len() == 1 => Type::Result(
            Box::new(infer_expr_type(&args[0], env, symbols)),
            Box::new(Type::Unknown),
        ),
        Expr::Call { callee, args, .. } if callee == "err" && args.len() == 1 => Type::Result(
            Box::new(Type::Unknown),
            Box::new(infer_expr_type(&args[0], env, symbols)),
        ),
        Expr::Call { callee, .. } if symbols.structs.contains_key(callee) => {
            Type::Struct(callee.clone())
        }
        Expr::Call { callee, .. } => symbols
            .functions
            .get(callee)
            .map(|sig| sig.return_type.clone())
            .unwrap_or(Type::Unknown),
        Expr::Try { expr, .. } => match infer_expr_type(expr, env, symbols) {
            Type::Result(ok, _) => *ok,
            _ => Type::Unknown,
        },
        Expr::ObjectLiteral { .. } => Type::Unknown,
        Expr::StructLiteral { name, .. } => Type::Struct(name.clone()),
        Expr::FieldAccess { object, field, .. } => match infer_expr_type(object, env, symbols) {
            Type::Struct(name) => symbols
                .structs
                .get(&name)
                .and_then(|fields| fields.get(field))
                .cloned()
                .unwrap_or(Type::Unknown),
            _ => Type::Unknown,
        },
        Expr::Unary { .. } => Type::Bool,
        Expr::ErrorVariantLiteral { error, .. } => Type::Struct(error.clone()),
    }
}

fn materialize_codegen_type(ty: Type) -> Type {
    match ty {
        Type::InferInt => Type::I32,
        Type::InferFloat => Type::F64,
        Type::Option(inner) => Type::Option(Box::new(materialize_codegen_type(*inner))),
        Type::Result(ok, err) => Type::Result(
            Box::new(materialize_codegen_type(*ok)),
            Box::new(materialize_codegen_type(*err)),
        ),
        other => other,
    }
}

fn positive_option_condition(
    condition: &Expr,
    env: &HashMap<String, Type>,
) -> Option<(String, Type)> {
    let Expr::Var { name, .. } = condition else {
        return None;
    };
    match env.get(name) {
        Some(Type::Option(inner)) => Some((name.clone(), *inner.clone())),
        _ => None,
    }
}

fn negative_option_condition(
    condition: &Expr,
    env: &HashMap<String, Type>,
) -> Option<(String, Type)> {
    let Expr::Unary {
        op: UnaryOp::Not,
        expr,
        ..
    } = condition
    else {
        return None;
    };
    let Expr::Var { name, .. } = expr.as_ref() else {
        return None;
    };
    match env.get(name) {
        Some(Type::Option(inner)) => Some((name.clone(), *inner.clone())),
        _ => None,
    }
}

fn always_returns_codegen(statements: &[Stmt]) -> bool {
    statements.iter().any(|stmt| match stmt {
        Stmt::Return { .. } => true,
        Stmt::If {
            then_body,
            else_body,
            ..
        } if !else_body.is_empty() => {
            always_returns_codegen(then_body) && always_returns_codegen(else_body)
        }
        _ => false,
    })
}

fn object_fields_for_codegen(expr: &Expr) -> Option<Vec<FieldValue>> {
    let Expr::ObjectLiteral { fields, .. } = expr else {
        return None;
    };
    let mut values = Vec::new();
    for field in fields {
        match field {
            ObjectField::Named { name, expr, span } => values.push(FieldValue {
                name: name.clone(),
                expr: expr.clone(),
                span: *span,
            }),
            ObjectField::Spread { .. } => return None,
        }
    }
    Some(values)
}

fn route_function_name(route: &RouteDecl) -> String {
    let mut name = http_method(route.method).to_string();
    for part in route.path.trim_matches('/').split('/') {
        if part.is_empty() {
            continue;
        }
        let cleaned = part
            .trim_matches('{')
            .trim_matches('}')
            .chars()
            .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
            .collect::<String>();
        if !cleaned.is_empty() {
            name.push('_');
            name.push_str(&cleaned);
        }
    }
    name.push_str("_route");
    name
}

fn route_params_name(route: &RouteDecl) -> String {
    format!("{}Params", route_type_base_name(route))
}

fn route_query_name(route: &RouteDecl) -> String {
    format!("{}Query", route_type_base_name(route))
}

fn route_error_status_fn(route: &RouteDecl) -> String {
    format!("{}_error_status", route_function_name(route))
}

fn route_type_base_name(route: &RouteDecl) -> String {
    let mut out = String::new();
    out.push_str(pascal(http_method(route.method)).as_str());
    for part in route.path.trim_matches('/').split('/') {
        let cleaned = part
            .trim_matches('{')
            .trim_matches('}')
            .chars()
            .filter(|ch| ch.is_ascii_alphanumeric() || *ch == '_')
            .collect::<String>();
        if !cleaned.is_empty() {
            out.push_str(&pascal(&cleaned));
        }
    }
    if out.is_empty() {
        "Route".to_string()
    } else {
        out
    }
}

fn pascal(text: &str) -> String {
    text.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!(
                    "{}{}",
                    first.to_ascii_uppercase(),
                    chars.collect::<String>()
                ),
                None => String::new(),
            }
        })
        .collect()
}

fn route_ok_expr(expr: &Expr) -> Option<&Expr> {
    let Expr::Call { callee, args, .. } = expr else {
        return None;
    };
    if callee == "ok" && args.len() == 1 {
        Some(&args[0])
    } else {
        None
    }
}

fn stmt_span(stmt: &Stmt) -> Span {
    match stmt {
        Stmt::Var { span, .. }
        | Stmt::Return { span, .. }
        | Stmt::If { span, .. }
        | Stmt::Expr { span, .. } => *span,
    }
}

fn status_code(status: u16) -> String {
    match status {
        200 => "StatusCode::OK".to_string(),
        201 => "StatusCode::CREATED".to_string(),
        204 => "StatusCode::NO_CONTENT".to_string(),
        400 => "StatusCode::BAD_REQUEST".to_string(),
        401 => "StatusCode::UNAUTHORIZED".to_string(),
        403 => "StatusCode::FORBIDDEN".to_string(),
        404 => "StatusCode::NOT_FOUND".to_string(),
        409 => "StatusCode::CONFLICT".to_string(),
        422 => "StatusCode::UNPROCESSABLE_ENTITY".to_string(),
        500 => "StatusCode::INTERNAL_SERVER_ERROR".to_string(),
        other => format!("StatusCode::from_u16({other}).unwrap()"),
    }
}

fn http_method(method: HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "get",
        HttpMethod::Post => "post",
        HttpMethod::Put => "put",
        HttpMethod::Patch => "patch",
        HttpMethod::Delete => "delete",
    }
}

fn rust_binary_op(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        BinaryOp::Eq => "==",
        BinaryOp::NotEq => "!=",
        BinaryOp::Lt => "<",
        BinaryOp::Gt => ">",
        BinaryOp::LtEq => "<=",
        BinaryOp::GtEq => ">=",
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::I32 => "i32".to_string(),
        Type::I64 => "i64".to_string(),
        Type::U32 => "u32".to_string(),
        Type::U64 => "u64".to_string(),
        Type::F32 => "f32".to_string(),
        Type::F64 => "f64".to_string(),
        Type::Bool => "bool".to_string(),
        Type::String => "String".to_string(),
        Type::Void => "()".to_string(),
        Type::Option(inner) => format!("Option<{}>", rust_type(inner)),
        Type::Result(ok, err) => format!("Result<{}, {}>", rust_type(ok), rust_type(err)),
        Type::Struct(name) => name.clone(),
        Type::None => "()".to_string(),
        Type::InferInt => "i32".to_string(),
        Type::InferFloat => "f64".to_string(),
        Type::Unknown => "()".to_string(),
    }
}
