use crate::ast::*;
use crate::diagnostics::{Diagnostic, DiagnosticBag, SourceFile, Span};
use crate::types::Type;

pub fn generate_rust(program: &Program) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Volt v0.1\n\n");

    for declaration in &program.declarations {
        match declaration {
            Decl::Import(_) => {}
            Decl::Type(type_decl) => {
                emit_type_decl(&mut out, type_decl);
                out.push('\n');
            }
            Decl::Function(function) => {
                emit_function(&mut out, function);
                out.push('\n');
            }
            Decl::Route(route) => {
                emit_route(&mut out, route);
                out.push('\n');
            }
        }
    }

    out
}

pub fn generate_axum_server(
    program: &Program,
    source: &SourceFile,
) -> Result<String, DiagnosticBag> {
    let mut lowering = AxumLowering {
        source,
        diagnostics: DiagnosticBag::new(),
    };
    let rust = lowering.generate(program);
    if lowering.diagnostics.is_empty() {
        Ok(rust)
    } else {
        Err(lowering.diagnostics)
    }
}

struct AxumLowering<'a> {
    source: &'a SourceFile,
    diagnostics: DiagnosticBag,
}

impl AxumLowering<'_> {
    fn generate(&mut self, program: &Program) -> String {
        let routes = program
            .declarations
            .iter()
            .filter_map(|decl| match decl {
                Decl::Route(route) => Some(route),
                _ => None,
            })
            .collect::<Vec<_>>();

        let mut out = String::new();
        out.push_str("// Generated by Volt v0.1\n");
        out.push_str("use axum::extract::{Path, Query, State};\n");
        out.push_str("use axum::http::StatusCode;\n");
        out.push_str("use axum::response::IntoResponse;\n");
        out.push_str("use axum::routing::{delete, get, patch, post, put};\n");
        out.push_str("use axum::Json;\n");
        out.push_str("use serde::{Deserialize, Serialize};\n\n");
        out.push_str("#[derive(Debug, Clone, Default)]\n");
        out.push_str("pub struct AppState {}\n\n");
        out.push_str("#[derive(Debug, Clone)]\n");
        out.push_str("pub struct RequestCtx {\n");
        out.push_str("    pub state: AppState,\n");
        out.push_str("}\n\n");
        out.push_str("impl RequestCtx {\n");
        out.push_str("    pub fn new(state: AppState) -> Self {\n");
        out.push_str("        Self { state }\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        for declaration in &program.declarations {
            if let Decl::Type(type_decl) = declaration {
                emit_api_type_decl(&mut out, type_decl);
                out.push('\n');
            }
        }

        for route in &routes {
            self.emit_route_params(&mut out, route);
            self.emit_route_query(&mut out, route);
        }

        for route in &routes {
            self.emit_route_handler(&mut out, route);
            out.push('\n');
        }

        self.emit_router(&mut out, &routes);
        emit_async_main(&mut out);
        out
    }

    fn emit_route_params(&mut self, out: &mut String, route: &RouteDecl) {
        if route.params.is_empty() {
            return;
        }
        out.push_str("#[derive(Debug, Clone, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", route_params_name(route)));
        for field in &route.params {
            out.push_str(&format!(
                "    pub {}: {},\n",
                field.name,
                rust_type(&field.ty)
            ));
        }
        out.push_str("}\n\n");
    }

    fn emit_route_query(&mut self, out: &mut String, route: &RouteDecl) {
        if route.query.is_empty() {
            return;
        }
        out.push_str("#[derive(Debug, Clone, Deserialize)]\n");
        out.push_str(&format!("pub struct {} {{\n", route_query_name(route)));
        for field in &route.query {
            out.push_str(&format!(
                "    pub {}: {},\n",
                field.name,
                rust_type(&field.ty)
            ));
        }
        out.push_str("}\n\n");
    }

    fn emit_route_handler(&mut self, out: &mut String, route: &RouteDecl) {
        let fn_name = route_function_name(route);
        out.push_str(&format!("async fn {fn_name}(\n"));
        if !route.params.is_empty() {
            out.push_str(&format!(
                "    Path(params): Path<{}>,\n",
                route_params_name(route)
            ));
        }
        if !route.query.is_empty() {
            out.push_str(&format!(
                "    Query(query): Query<{}>,\n",
                route_query_name(route)
            ));
        }
        out.push_str("    State(state): State<AppState>,\n");
        if let Some(body_type) = &route.body_type {
            out.push_str(&format!(
                "    Json(body): Json<{}>,\n",
                rust_type(body_type)
            ));
        }
        out.push_str(") -> impl IntoResponse {\n");
        out.push_str("    let ctx = RequestCtx::new(state);\n");
        out.push_str("    let _ = &ctx;\n");

        let Some(return_expr) = self.emit_route_statements(out, &route.statements) else {
            out.push_str("    StatusCode::INTERNAL_SERVER_ERROR.into_response()\n");
            out.push_str("}\n");
            return;
        };

        out.push_str(&format!("    let value = {return_expr};\n"));
        out.push_str(&format!(
            "    ({}, Json(value)).into_response()\n",
            status_code(route.ok_status)
        ));
        out.push_str("}\n");
    }

    fn emit_route_statements(&mut self, out: &mut String, statements: &[Stmt]) -> Option<String> {
        let mut return_expr = None;
        for stmt in statements {
            match stmt {
                Stmt::Var {
                    mutable,
                    name,
                    expr,
                    span,
                    ..
                } => {
                    let Some(value) = self.lower_route_expr(expr) else {
                        self.unsupported(*span);
                        continue;
                    };
                    let mutability = if *mutable { " mut" } else { "" };
                    out.push_str(&format!("    let{mutability} {name} = {value};\n"));
                }
                Stmt::Return { expr, span } => {
                    let Some(ok_expr) = route_ok_expr(expr) else {
                        self.unsupported(*span);
                        continue;
                    };
                    return_expr = self.lower_route_expr(ok_expr);
                    if return_expr.is_none() {
                        self.unsupported(ok_expr.span());
                    }
                }
                _ => self.unsupported(stmt_span(stmt)),
            }
        }
        return_expr
    }

    fn lower_route_expr(&mut self, expr: &Expr) -> Option<String> {
        match expr {
            Expr::Int { value, .. } => Some(value.to_string()),
            Expr::Float { value, .. } => Some(value.to_string()),
            Expr::String { value, .. } => Some(format!("{value:?}.to_string()")),
            Expr::Bool { value, .. } => Some(value.to_string()),
            Expr::Var { name, .. } => Some(name.clone()),
            Expr::FieldAccess { object, field, .. } => {
                let base = self.lower_route_expr(object)?;
                Some(format!("{base}.{field}"))
            }
            Expr::StructLiteral { name, fields, .. } => {
                let mut parts = Vec::new();
                for field in fields {
                    let value = self.lower_route_expr(&field.expr)?;
                    parts.push(format!("{}: {}", field.name, value));
                }
                Some(format!("{name} {{ {} }}", parts.join(", ")))
            }
            Expr::Call { callee, args, .. } if callee != "ok" && callee != "err" => {
                let mut lowered = Vec::new();
                for arg in args {
                    lowered.push(self.lower_route_expr(arg)?);
                }
                Some(format!("{callee}({})", lowered.join(", ")))
            }
            _ => None,
        }
    }

    fn emit_router(&mut self, out: &mut String, routes: &[&RouteDecl]) {
        out.push_str("fn build_router(state: AppState) -> axum::Router {\n");
        out.push_str("    axum::Router::new()\n");
        for route in routes {
            out.push_str(&format!(
                "        .route({:?}, {}({}))\n",
                route.path,
                http_method(route.method),
                route_function_name(route)
            ));
        }
        out.push_str("        .with_state(state)\n");
        out.push_str("}\n\n");
    }

    fn unsupported(&mut self, span: Span) {
        self.diagnostics.push(Diagnostic::new(
            "EHTTPLOWER001",
            "unsupported route body expression for Axum lowering",
            self.source,
            span,
            Some("use const bindings and `return ok(...)` with literals, field access, calls, or struct literals".to_string()),
        ));
    }
}

fn emit_api_type_decl(out: &mut String, type_decl: &TypeDecl) {
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {} {{\n", type_decl.name));
    for field in &type_decl.fields {
        out.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            rust_type(&field.ty)
        ));
    }
    out.push_str("}\n");
}

fn emit_async_main(out: &mut String) {
    out.push_str("#[tokio::main]\n");
    out.push_str("async fn main() {\n");
    out.push_str("    let state = AppState::default();\n");
    out.push_str("    let app = build_router(state);\n\n");
    out.push_str("    let addr = std::env::var(\"VLT_ADDR\")\n");
    out.push_str("        .unwrap_or_else(|_| \"0.0.0.0:8080\".to_string());\n\n");
    out.push_str("    let listener = tokio::net::TcpListener::bind(&addr)\n");
    out.push_str("        .await\n");
    out.push_str("        .expect(\"failed to bind TCP listener\");\n\n");
    out.push_str("    println!(\"Volt server listening on http://{}\", addr);\n\n");
    out.push_str("    axum::serve(listener, app)\n");
    out.push_str("        .await\n");
    out.push_str("        .expect(\"server failed\");\n");
    out.push_str("}\n");
}

fn emit_route(out: &mut String, route: &RouteDecl) {
    let fn_name = route_function_name(route);
    out.push_str("// Native Volt route scaffold.\n");
    out.push_str("// Wire this function into an Axum Router once the HTTP runtime lands.\n");
    out.push_str(&format!(
        "// route {} \"{}\" -> {} {}\n",
        http_method(route.method).to_uppercase(),
        route.path,
        route.ok_status,
        rust_type(&route.ok_type)
    ));
    if !route.effects.is_empty() {
        out.push_str(&format!("// effects: {}\n", route.effects.join(", ")));
    }
    out.push_str(&format!("async fn {fn_name}(\n"));
    for field in &route.params {
        out.push_str(&format!(
            "    // axum::extract::Path({}): axum::extract::Path<{}>,\n",
            field.name,
            rust_type(&field.ty)
        ));
    }
    if let Some(body_type) = &route.body_type {
        out.push_str(&format!(
            "    // axum::Json(body): axum::Json<{}>,\n",
            rust_type(body_type)
        ));
    }
    out.push_str("    // axum::extract::State(state): axum::extract::State<AppState>,\n");
    out.push_str(") -> impl axum::response::IntoResponse {\n");
    out.push_str("    // TODO(v0.1): lower Volt route statements into Axum handler code.\n");
    out.push_str(&format!(
        "    // Router::new().route(\"{}\", axum::routing::{}({fn_name}))\n",
        route.path,
        http_method(route.method)
    ));
    out.push_str("    axum::http::StatusCode::NOT_IMPLEMENTED\n");
    out.push_str("}\n");
}

fn emit_type_decl(out: &mut String, type_decl: &TypeDecl) {
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("struct {} {{\n", type_decl.name));
    for field in &type_decl.fields {
        out.push_str(&format!("    {}: {},\n", field.name, rust_type(&field.ty)));
    }
    out.push_str("}\n");
}

fn emit_function(out: &mut String, function: &FunctionDecl) {
    let params = function
        .params
        .iter()
        .map(|param| format!("{}: {}", param.name, rust_type(&param.ty)))
        .collect::<Vec<_>>()
        .join(", ");

    if matches!(function.return_type, Type::Void) {
        out.push_str(&format!("fn {}({}) {{\n", function.name, params));
    } else {
        out.push_str(&format!(
            "fn {}({}) -> {} {{\n",
            function.name,
            params,
            rust_type(&function.return_type)
        ));
    }

    for stmt in &function.body {
        emit_stmt(out, stmt, 1);
    }
    out.push_str("}\n");
}

fn emit_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    let pad = "    ".repeat(indent);
    match stmt {
        Stmt::Var {
            mutable,
            name,
            expr,
            ..
        } => {
            let mutability = if *mutable { " mut" } else { "" };
            out.push_str(&format!(
                "{pad}let{mutability} {name} = {};\n",
                emit_expr(expr)
            ));
        }
        Stmt::Return { expr, .. } => {
            out.push_str(&format!("{pad}return {};\n", emit_expr(expr)));
        }
        Stmt::If {
            condition,
            then_body,
            else_body,
            ..
        } => {
            out.push_str(&format!("{pad}if {} {{\n", emit_expr(condition)));
            for stmt in then_body {
                emit_stmt(out, stmt, indent + 1);
            }
            if else_body.is_empty() {
                out.push_str(&format!("{pad}}}\n"));
            } else {
                out.push_str(&format!("{pad}}} else {{\n"));
                for stmt in else_body {
                    emit_stmt(out, stmt, indent + 1);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
        }
        Stmt::Expr { expr, .. } => {
            out.push_str(&format!("{pad}{};\n", emit_expr(expr)));
        }
    }
}

fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Int { value, .. } => value.to_string(),
        Expr::Float { value, .. } => {
            let text = value.to_string();
            if text.contains('.') {
                text
            } else {
                format!("{text}.0")
            }
        }
        Expr::String { value, .. } => format!("{:?}.to_string()", value),
        Expr::Bool { value, .. } => value.to_string(),
        Expr::Var { name, .. } => name.clone(),
        Expr::Binary {
            left, op, right, ..
        } => format!(
            "{} {} {}",
            emit_expr(left),
            rust_binary_op(*op),
            emit_expr(right)
        ),
        Expr::Call { callee, args, .. } => match callee.as_str() {
            "print" => format!("println!(\"{{:?}}\", {})", emit_expr(&args[0])),
            "ok" => format!("Ok({})", emit_expr(&args[0])),
            "err" => format!("Err({})", emit_expr(&args[0])),
            _ => format!(
                "{}({})",
                callee,
                args.iter().map(emit_expr).collect::<Vec<_>>().join(", ")
            ),
        },
        Expr::Try { expr, .. } => format!("{}?", emit_expr(expr)),
        Expr::ObjectLiteral { fields, .. } => {
            let body = fields
                .iter()
                .map(|field| match field {
                    ObjectField::Named { name, expr, .. } => format!("{name}: {}", emit_expr(expr)),
                    ObjectField::Spread { expr, .. } => format!("..{}", emit_expr(expr)),
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {body} }}")
        }
        Expr::StructLiteral { name, fields, .. } => {
            let body = fields
                .iter()
                .map(|field| format!("{}: {}", field.name, emit_expr(&field.expr)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{name} {{ {body} }}")
        }
        Expr::FieldAccess { object, field, .. } => format!("{}.{}", emit_expr(object), field),
    }
}

fn route_function_name(route: &RouteDecl) -> String {
    let mut name = http_method(route.method).to_string();
    for part in route.path.trim_matches('/').split('/') {
        if part.is_empty() {
            continue;
        }
        let cleaned = part
            .trim_matches('{')
            .trim_matches('}')
            .chars()
            .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
            .collect::<String>();
        if !cleaned.is_empty() {
            name.push('_');
            name.push_str(&cleaned);
        }
    }
    name.push_str("_route");
    name
}

fn route_params_name(route: &RouteDecl) -> String {
    format!("{}Params", route_type_base_name(route))
}

fn route_query_name(route: &RouteDecl) -> String {
    format!("{}Query", route_type_base_name(route))
}

fn route_type_base_name(route: &RouteDecl) -> String {
    let mut out = String::new();
    out.push_str(pascal(http_method(route.method)).as_str());
    for part in route.path.trim_matches('/').split('/') {
        let cleaned = part
            .trim_matches('{')
            .trim_matches('}')
            .chars()
            .filter(|ch| ch.is_ascii_alphanumeric() || *ch == '_')
            .collect::<String>();
        if !cleaned.is_empty() {
            out.push_str(&pascal(&cleaned));
        }
    }
    if out.is_empty() {
        "Route".to_string()
    } else {
        out
    }
}

fn pascal(text: &str) -> String {
    text.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!(
                    "{}{}",
                    first.to_ascii_uppercase(),
                    chars.collect::<String>()
                ),
                None => String::new(),
            }
        })
        .collect()
}

fn route_ok_expr(expr: &Expr) -> Option<&Expr> {
    let Expr::Call { callee, args, .. } = expr else {
        return None;
    };
    if callee == "ok" && args.len() == 1 {
        Some(&args[0])
    } else {
        None
    }
}

fn stmt_span(stmt: &Stmt) -> Span {
    match stmt {
        Stmt::Var { span, .. }
        | Stmt::Return { span, .. }
        | Stmt::If { span, .. }
        | Stmt::Expr { span, .. } => *span,
    }
}

fn status_code(status: u16) -> String {
    match status {
        200 => "StatusCode::OK".to_string(),
        201 => "StatusCode::CREATED".to_string(),
        204 => "StatusCode::NO_CONTENT".to_string(),
        400 => "StatusCode::BAD_REQUEST".to_string(),
        401 => "StatusCode::UNAUTHORIZED".to_string(),
        403 => "StatusCode::FORBIDDEN".to_string(),
        404 => "StatusCode::NOT_FOUND".to_string(),
        409 => "StatusCode::CONFLICT".to_string(),
        422 => "StatusCode::UNPROCESSABLE_ENTITY".to_string(),
        500 => "StatusCode::INTERNAL_SERVER_ERROR".to_string(),
        other => format!("StatusCode::from_u16({other}).unwrap()"),
    }
}

fn http_method(method: HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "get",
        HttpMethod::Post => "post",
        HttpMethod::Put => "put",
        HttpMethod::Patch => "patch",
        HttpMethod::Delete => "delete",
    }
}

fn rust_binary_op(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        BinaryOp::Eq => "==",
        BinaryOp::NotEq => "!=",
        BinaryOp::Lt => "<",
        BinaryOp::Gt => ">",
        BinaryOp::LtEq => "<=",
        BinaryOp::GtEq => ">=",
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::I32 => "i32".to_string(),
        Type::I64 => "i64".to_string(),
        Type::U32 => "u32".to_string(),
        Type::U64 => "u64".to_string(),
        Type::F32 => "f32".to_string(),
        Type::F64 => "f64".to_string(),
        Type::Bool => "bool".to_string(),
        Type::String => "String".to_string(),
        Type::Void => "()".to_string(),
        Type::Result(ok, err) => format!("Result<{}, {}>", rust_type(ok), rust_type(err)),
        Type::Struct(name) => name.clone(),
        Type::InferInt => "i32".to_string(),
        Type::InferFloat => "f64".to_string(),
        Type::Unknown => "()".to_string(),
    }
}
